In [1]:
from utility import common_load_parquet_dataset
import pandas as pd
from pathlib import Path
import time

In [2]:
DATA_PATH = Path(
    r"E:\repos\LLM_traffic_query\tests\energy_prediction\dataset\ashrae-energy-prediction\processed_features\ashrae_train_cleaned_plus_manual_features"
)
df = common_load_parquet_dataset(DATA_PATH)
print(df.columns)

Index(['building_id', 'timestamp', 'meter_reading', 'ts_idx', 'pair_id',
       'primary_use', 'square_feet', 'year_built', 'floor_count',
       'timestamp_gmt', 'time_diff_hours', 'air_temperature', 'cloud_coverage',
       'dew_temperature', 'precip_depth_1_hr', 'sea_level_pressure',
       'wind_direction', 'wind_speed', 'is_na_holiday', 'is_eu_holiday',
       'hour_sin', 'hour_cos', 'dayofweek', 'doy_sin', 'doy_cos', 'is_weekend',
       'is_holiday_any', 'is_business_hours', 'CDH_18C', 'HDH_18C',
       'is_hot_24C', 'is_cold_10C', 'dewpoint_depression', 'log_sqft',
       'year_built_clipped', 'site_id', 'meter'],
      dtype='str')

In [3]:
# Old code retained for reference.
# from expert_feature_extractor import extract_expert_features
#
# cache = {}
# df_expert = extract_expert_features(df, cache=cache)

# Revised: load all supplementary ablation groups.
from expert_feature_extractor import extract_expert_features
from supplementary_feature_rank2 import extract_rank2_weather_stats_features
from supplementary_feature_rank25 import extract_rank25_missingness_features

try:
    from supplementary_feature_rank4_revised import extract_rank4_features
except ImportError:
    from supplementary_feature_rank4 import extract_rank4_features

try:
    from supplementary_feature_rank5_revised import extract_rank5_mma_features
except ImportError:
    from supplementary_feature_rank5 import extract_rank5_mma_features

SUPPLEMENTARY_EXCLUDE_BUILDING_ID = True

feature_group_frames = {}
feature_group_caches = {}

cache_expert = {}
feature_group_frames["expert"] = extract_expert_features(df, cache=cache_expert)
feature_group_caches["expert"] = cache_expert

cache_rank2 = {}
feature_group_frames["rank2"] = extract_rank2_weather_stats_features(
    df,
    cache=cache_rank2,
    mode="fit_transform",
    label_col="meter_reading",
    exclude_building_id=SUPPLEMENTARY_EXCLUDE_BUILDING_ID,
)
feature_group_caches["rank2"] = cache_rank2

cache_rank4 = {}
feature_group_frames["rank4"] = extract_rank4_features(
    df,
    cache=cache_rank4,
    mode="fit_transform",
    label_col="meter_reading",
    exclude_building_id=SUPPLEMENTARY_EXCLUDE_BUILDING_ID,
)
feature_group_caches["rank4"] = cache_rank4

cache_rank5 = {}
feature_group_frames["rank5"] = extract_rank5_mma_features(
    df,
    cache=cache_rank5,
    mode="fit_transform",
    label_col="meter_reading",
    exclude_building_id=SUPPLEMENTARY_EXCLUDE_BUILDING_ID,
)
feature_group_caches["rank5"] = cache_rank5

cache_rank25 = {}
feature_group_frames["rank25"] = extract_rank25_missingness_features(
    df,
    cache=cache_rank25,
    mode="fit_transform",
    label_col="meter_reading",
)
feature_group_caches["rank25"] = cache_rank25

for group_name, frame in feature_group_frames.items():
    print(f"{group_name}: shape={frame.shape}")

[rank5]: Skipping building features due to exclude_building_id=True or missing building_id column.
expert: shape=(19544538, 16)
rank2: shape=(19544538, 24)
rank4: shape=(19544538, 62)
rank5: shape=(19544538, 8)
rank25: shape=(19544538, 17)

In [4]:
# Old code retained for reference.
# df_full = pd.concat([df, df_expert], axis=1)

# Revised: concatenate baseline with all supplementary groups for per-feature analysis.
feature_group_order = ["expert", "rank2", "rank4", "rank5", "rank25"]
df_full = pd.concat([df] + [feature_group_frames[g] for g in feature_group_order], axis=1)
print(df_full.shape)

(19544538, 164)

In [5]:
df_full.columns

Index(['building_id', 'timestamp', 'meter_reading', 'ts_idx', 'pair_id',
       'primary_use', 'square_feet', 'year_built', 'floor_count',
       'timestamp_gmt',
       ...
       'r25_site_missing_rate_precip_depth_1_hr',
       'r25_is_missing_sea_level_pressure',
       'r25_site_missing_rate_sea_level_pressure',
       'r25_is_missing_wind_direction', 'r25_site_missing_rate_wind_direction',
       'r25_is_missing_wind_speed', 'r25_site_missing_rate_wind_speed',
       'r25_missing_weather_count', 'r25_missing_weather_frac',
       'r25_site_any_missing_rate'],
      dtype='str', length=164)

In [6]:
# Old code retained for reference.
# target_col = "meter_reading"
# cols_base = df.columns.tolist()
# cols_base.remove(target_col)
# cols_base.remove("timestamp")
# cols_exp = df_expert.columns.tolist()
# cols_full = cols_base + cols_exp
# print("full cols:", cols_full)

target_col = "meter_reading"
cols_base = df.columns.tolist()
if target_col in cols_base:
    cols_base.remove(target_col)
if "timestamp" in cols_base:
    cols_base.remove("timestamp")

feature_group_cols = {name: frame.columns.tolist() for name, frame in feature_group_frames.items()}
cols_exp = feature_group_cols["expert"]
cols_rank2 = feature_group_cols["rank2"]
cols_rank4 = feature_group_cols["rank4"]
cols_rank5 = feature_group_cols["rank5"]
cols_rank25 = feature_group_cols["rank25"]

cols_full = cols_base + cols_exp + cols_rank2 + cols_rank4 + cols_rank5 + cols_rank25

feature_origin_map = {c: "base" for c in cols_base}
for group_name, cols in feature_group_cols.items():
    for c in cols:
        feature_origin_map[c] = group_name

print("n base:", len(cols_base))
for group_name in feature_group_order:
    print(f"n {group_name}:", len(feature_group_cols[group_name]))
print("n full:", len(cols_full))

n base: 35
n expert: 16
n rank2: 24
n rank4: 62
n rank5: 8
n rank25: 17
n full: 162

In [7]:
import numpy as np
import pandas as pd

from patsy import dmatrix, build_design_matrices

from sklearn.dummy import DummyRegressor
from sklearn.feature_selection import mutual_info_regression
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import OneHotEncoder

In [8]:
TRUE_STRINGS = {"true", "1", "yes", "y", "t"}
FALSE_STRINGS = {"false", "0", "no", "n", "f"}


def _make_onehot_encoder(dtype=np.float32):
    """
    Return a sparse OneHotEncoder.
    New sklearn uses sparse_output=...; older sklearn uses sparse=...
    """
    try:
        return OneHotEncoder(
            handle_unknown="ignore",
            sparse_output=True,
            dtype=dtype,
        )
    except TypeError:
        return OneHotEncoder(
            handle_unknown="ignore",
            sparse=True,
            dtype=dtype,
        )


def normalize_boolean_series(s: pd.Series) -> pd.Series:
    """
    Normalize bool-like values to strings 'True'/'False', keep NaN as NaN.
    """

    def _map(v):
        if pd.isna(v):
            return np.nan
        if isinstance(v, (bool, np.bool_)):
            return "True" if bool(v) else "False"

        txt = str(v).strip().lower()
        if txt in TRUE_STRINGS:
            return "True"
        if txt in FALSE_STRINGS:
            return "False"
        return str(v)

    return s.map(_map)


def infer_feature_type(s: pd.Series) -> str:
    """
    Conservative feature type inference:
      - bool / nullable bool / binary {0,1} -> boolean
      - object/string/category -> categorical
      - other numeric -> numeric
    """
    s_nonnull = s.dropna()
    if s_nonnull.empty:
        return "categorical"

    # Native / nullable boolean dtype
    if pd.api.types.is_bool_dtype(s):
        return "boolean"

    # Numeric columns: only pure binary {0,1} are treated as boolean
    if pd.api.types.is_numeric_dtype(s):
        uniq = pd.unique(s_nonnull)
        if len(uniq) <= 2:
            try:
                uniq_as_float = set(pd.Series(uniq).astype(float).tolist())
                if uniq_as_float.issubset({0.0, 1.0}):
                    return "boolean"
            except Exception:
                pass
        return "numeric"

    # object/string/category columns
    if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
        s_norm = normalize_boolean_series(s_nonnull).dropna().astype(str)
        if not s_norm.empty:
            uniq = set(s_norm.unique().tolist())
            if uniq.issubset({"True", "False"}):
                return "boolean"
        return "categorical"

    # Fallback
    return "categorical"


def prepare_discrete_series_for_mi(s: pd.Series, feature_type: str) -> np.ndarray:
    """
    For boolean/categorical MI:
      - fill NaN with '__MISSING__'
      - factorize to integer codes
    """
    if feature_type == "boolean":
        s = normalize_boolean_series(s)
    s = s.astype("object").where(s.notna(), "__MISSING__").astype(str)
    codes, _ = pd.factorize(s, sort=True)
    return codes.astype(int)


def get_feature_group(col: str) -> str:
    if col in cols_base:
        return "base"
    if col in cols_exp:
        return "exp"
    return "other"


# Revised group resolver for expanded ablations.
# def get_feature_group(col: str):
#     if col in cols_base:
#         return "base"
#     if col in cols_exp:
#         return "exp"
#     return "other"


def get_feature_group(col: str) -> str:
    return feature_origin_map.get(col, "other")

In [9]:
# Old code retained for reference.
# detected_feature_types = {col: infer_feature_type(df_full[col]) for col in [c for c in cols_full if c != target_col]}
#
# detected_feature_types

detected_feature_types = {col: infer_feature_type(df_full[col]) for col in [c for c in cols_full if c != target_col]}

pd.Series(detected_feature_types).groupby(
    pd.Series({k: get_feature_group(k) for k in detected_feature_types})
).size().sort_index()

C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):

base      35
expert    16
rank2     24
rank25    17
rank4     62
rank5      8
dtype: int64

In [10]:
def mutual_info_single_feature(x: pd.Series, y: pd.Series, feature_type: str, random_state: int = 42) -> float:
    """
    Per-feature MI against numeric target.
    NaN handling:
      - numeric: median imputation
      - boolean/categorical: '__MISSING__' category
    """
    mask = y.notna()
    x = x.loc[mask].reset_index(drop=True)
    y = pd.to_numeric(y.loc[mask], errors="coerce").reset_index(drop=True)

    valid_y = y.notna()
    x = x.loc[valid_y].reset_index(drop=True)
    y = y.loc[valid_y].to_numpy()

    if len(y) == 0:
        return np.nan

    if feature_type == "numeric":
        x_num = pd.to_numeric(x, errors="coerce")

        # constant or all-missing -> MI = 0
        if x_num.notna().sum() == 0 or x_num.nunique(dropna=True) <= 1:
            return 0.0

        fill_value = x_num.median()
        x_num = x_num.fillna(fill_value).to_numpy().reshape(-1, 1)

        mi = mutual_info_regression(x_num, y, discrete_features=False, random_state=random_state)[0]
        return float(mi)

    # boolean / categorical
    x_disc = prepare_discrete_series_for_mi(x, feature_type)
    if pd.Series(x_disc).nunique(dropna=False) <= 1:
        return 0.0

    mi = mutual_info_regression(x_disc.reshape(-1, 1), y, discrete_features=True, random_state=random_state)[0]
    return float(mi)

In [11]:
def predict_numeric_probe_train_test(x_train: pd.Series, y_train: pd.Series, x_test: pd.Series, spline_df: int = 4):
    """
    Numeric feature probe:
      - natural cubic spline with df=4 if enough unique values
      - linear fallback if too few unique values
      - mean fallback if constant / all-missing
    Includes a missingness indicator.
    """
    x_train = pd.to_numeric(x_train, errors="coerce")
    x_test = pd.to_numeric(x_test, errors="coerce")
    y_train = pd.to_numeric(y_train, errors="coerce")

    if len(y_train) == 0:
        return np.array([], dtype=np.float32), "mean_fallback"

    if x_train.notna().sum() == 0:
        model = DummyRegressor(strategy="mean")
        model.fit(np.zeros((len(y_train), 1), dtype=np.float32), y_train)
        pred = model.predict(np.zeros((len(x_test), 1), dtype=np.float32))
        return pred.astype(np.float32, copy=False), "mean_fallback"

    n_unique = x_train.nunique(dropna=True)
    fill_value = x_train.median()

    x_train_imp = x_train.fillna(fill_value)
    x_test_imp = x_test.fillna(fill_value)

    miss_train = x_train.isna().astype(np.float32).to_numpy().reshape(-1, 1)
    miss_test = x_test.isna().astype(np.float32).to_numpy().reshape(-1, 1)

    if n_unique <= 1:
        model = DummyRegressor(strategy="mean")
        model.fit(np.zeros((len(y_train), 1), dtype=np.float32), y_train)
        pred = model.predict(np.zeros((len(x_test), 1), dtype=np.float32))
        return pred.astype(np.float32, copy=False), "mean_fallback"

    if n_unique >= spline_df:
        spline_train = dmatrix(f"cr(x, df={spline_df}) - 1", {"x": x_train_imp.to_numpy()}, return_type="dataframe")
        design_info = spline_train.design_info
        spline_test = build_design_matrices([design_info], {"x": x_test_imp.to_numpy()})[0]

        X_train = np.hstack([np.asarray(spline_train, dtype=np.float32), miss_train]).astype(np.float32, copy=False)
        X_test = np.hstack([np.asarray(spline_test, dtype=np.float32), miss_test]).astype(np.float32, copy=False)

        model = LinearRegression()
        model.fit(X_train, y_train)
        pred = model.predict(X_test)
        return pred.astype(np.float32, copy=False), f"natural_cubic_spline_df{spline_df}"

    X_train = np.hstack([x_train_imp.to_numpy(dtype=np.float32).reshape(-1, 1), miss_train]).astype(
        np.float32, copy=False
    )
    X_test = np.hstack([x_test_imp.to_numpy(dtype=np.float32).reshape(-1, 1), miss_test]).astype(np.float32, copy=False)

    model = LinearRegression()
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    return pred.astype(np.float32, copy=False), "linear_fallback"


def predict_discrete_probe_train_test(
    x_train: pd.Series, y_train: pd.Series, x_test: pd.Series, feature_type: str, ridge_alpha: float = 1.0
):
    """
    Boolean/categorical feature probe:
      - fill NaN as '__MISSING__'
      - sparse one-hot encode
      - sparse-capable ridge regression
    """
    if feature_type == "boolean":
        x_train = normalize_boolean_series(x_train)
        x_test = normalize_boolean_series(x_test)

    x_train = x_train.astype("object").where(x_train.notna(), "__MISSING__").astype(str)
    x_test = x_test.astype("object").where(x_test.notna(), "__MISSING__").astype(str)

    enc = _make_onehot_encoder(dtype=np.float32)

    X_train = enc.fit_transform(x_train.to_frame())  # sparse CSR
    X_test = enc.transform(x_test.to_frame())  # sparse CSR

    if X_train.shape[1] <= 1:
        model = DummyRegressor(strategy="mean")
        model.fit(np.zeros((len(y_train), 1), dtype=np.float32), y_train)
        pred = model.predict(np.zeros((len(x_test), 1), dtype=np.float32))
        return pred.astype(np.float32, copy=False), "mean_fallback"

    model = Ridge(alpha=ridge_alpha, solver="lsqr")
    model.fit(X_train, y_train.to_numpy(dtype=np.float32))
    pred = model.predict(X_test)

    if feature_type == "boolean":
        return np.asarray(pred, dtype=np.float32), "boolean_factor_ridge_sparse"
    return np.asarray(pred, dtype=np.float32), "categorical_factor_ridge_sparse"


def cross_validated_univariate_probe(
    x: pd.Series,
    y: pd.Series,
    feature_type: str,
    n_splits: int = 3,
    random_state: int = 42,
    spline_df: int = 4,
    ridge_alpha: float = 1.0,
    feature_name: str = None,
    verbose: int = 1,
):
    """
    Cross-validated per-feature probe score.
    Returns out-of-fold R^2 and RMSE.
    """
    mask = y.notna()
    x = x.loc[mask].reset_index(drop=True)
    y = pd.to_numeric(y.loc[mask], errors="coerce").reset_index(drop=True)

    valid_y = y.notna()
    x = x.loc[valid_y].reset_index(drop=True)
    y = y.loc[valid_y].reset_index(drop=True)

    n = len(y)
    fname = feature_name if feature_name is not None else "<unknown>"

    if n < 2:
        return {
            "probe_cv_r2": np.nan,
            "probe_cv_rmse": np.nan,
            "probe_model": "not_enough_rows",
            "n_rows_used": n,
        }

    n_splits_eff = min(n_splits, n)
    if n_splits_eff < 2:
        return {
            "probe_cv_r2": np.nan,
            "probe_cv_rmse": np.nan,
            "probe_model": "not_enough_rows",
            "n_rows_used": n,
        }

    cv = KFold(n_splits=n_splits_eff, shuffle=True, random_state=random_state)
    oof_pred = np.full(n, np.nan, dtype=np.float32)
    model_names = []

    probe_t0 = time.perf_counter()

    for fold_idx, (train_idx, test_idx) in enumerate(cv.split(np.arange(n)), start=1):
        fold_t0 = time.perf_counter()

        # if verbose:
        #     print(
        #         f"      fold {fold_idx}/{n_splits_eff} | "
        #         f"feature={fname} | type={feature_type} | "
        #         f"train={len(train_idx):,} test={len(test_idx):,}"
        #     )

        x_train = x.iloc[train_idx]
        y_train = y.iloc[train_idx]
        x_test = x.iloc[test_idx]

        if feature_type == "numeric":
            pred, model_name = predict_numeric_probe_train_test(
                x_train=x_train, y_train=y_train, x_test=x_test, spline_df=spline_df
            )
        else:
            pred, model_name = predict_discrete_probe_train_test(
                x_train=x_train, y_train=y_train, x_test=x_test, feature_type=feature_type, ridge_alpha=ridge_alpha
            )

        oof_pred[test_idx] = pred
        model_names.append(model_name)

        # if verbose:
        #     print(f"        fold done in {time.perf_counter() - fold_t0:.1f}s | " f"model={model_name}")

    probe_r2 = r2_score(y, oof_pred)
    probe_rmse = np.sqrt(mean_squared_error(y, oof_pred))
    probe_model = pd.Series(model_names).mode().iloc[0]

    if verbose:
        print(
            f"      probe finished for {fname} in {time.perf_counter() - probe_t0:.1f}s | "
            f"R2={probe_r2:.6f} | RMSE={probe_rmse:.6f}"
        )

    return {
        "probe_cv_r2": float(probe_r2),
        "probe_cv_rmse": float(probe_rmse),
        "probe_model": probe_model,
        "n_rows_used": int(n),
    }

In [12]:
# Old code retained for reference.
# df_full["building_id"] = df_full["building_id"].astype("category")
# df_full["pair_id"] = df_full["pair_id"].astype("category")
# df_full["ts_idx"] = df_full["ts_idx"].astype("category")  # only if it is an index/code, not ordered numeric meaning

for cat_col in ["building_id", "pair_id", "ts_idx"]:
    if cat_col in df_full.columns:
        df_full[cat_col] = df_full[cat_col].astype("category")

In [13]:
# Features to score: everything except the target
feature_cols = [c for c in cols_full if c != target_col]

# Strongly recommended for 20M rows
sample_size_per_feature = 2000000  # set None to use all rows
cv_splits_per_feature = 3
random_state = 42

# Shared valid target rows
y_full = pd.to_numeric(df_full[target_col], errors="coerce")
valid_idx = y_full.index[y_full.notna()]

# Shared sample across all features for fair comparison and much faster runtime
if sample_size_per_feature is not None and len(valid_idx) > sample_size_per_feature:
    sampled_idx = (
        pd.Series(valid_idx).sample(n=sample_size_per_feature, random_state=random_state).sort_values().to_numpy()
    )
else:
    sampled_idx = valid_idx.to_numpy()

print(f"Using {len(sampled_idx):,} rows for per-feature MI/probe scoring.")

y_all = pd.to_numeric(df_full.loc[sampled_idx, target_col], errors="coerce").reset_index(drop=True)

rows = []
total_t0 = time.perf_counter()

for i, col in enumerate(feature_cols, start=1):
    feat_t0 = time.perf_counter()

    s = df_full.loc[sampled_idx, col].reset_index(drop=True)
    feature_type = infer_feature_type(s)

    print(
        f"[{i}/{len(feature_cols)}] feature={col} | "
        f"type={feature_type} | "
        f"missing={s.isna().mean():.4f} | "
        f"unique_non_null={s.nunique(dropna=True):,}"
    )

    mi_t0 = time.perf_counter()
    mi_score = mutual_info_single_feature(x=s, y=y_all, feature_type=feature_type, random_state=random_state)
    print(f"    MI done in {time.perf_counter() - mi_t0:.1f}s | mi_score={mi_score:.6f}")

    probe_stats = cross_validated_univariate_probe(
        x=s,
        y=y_all,
        feature_type=feature_type,
        n_splits=cv_splits_per_feature,
        random_state=random_state,
        spline_df=4,
        ridge_alpha=1.0,
        feature_name=col,
        verbose=True,
    )

    rows.append(
        {
            "feature": col,
            "feature_group": get_feature_group(col),
            "source_ablation_group": get_feature_group(col),
            "feature_type": feature_type,
            "missing_rate": float(s.isna().mean()),
            "n_unique_non_null": int(s.nunique(dropna=True)),
            "mi_score": mi_score,
            **probe_stats,
        }
    )

    print(
        f"    feature finished in {time.perf_counter() - feat_t0:.1f}s | "
        f"elapsed total {time.perf_counter() - total_t0:.1f}s"
    )
    print("-" * 80)

per_feature_results = pd.DataFrame(rows)

per_feature_results = per_feature_results.sort_values(
    by=["feature_group", "probe_cv_r2", "mi_score"], ascending=[True, False, False]
).reset_index(drop=True)

per_feature_results

Using 2,000,000 rows for per-feature MI/probe scoring.

C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):

[1/162] feature=building_id | type=categorical | missing=0.0000 | unique_non_null=1,425
    MI done in 15.4s | mi_score=1.629829
      probe finished for building_id in 2.2s | R2=0.265496 | RMSE=2121.416154
    feature finished in 17.9s | elapsed total 17.9s
--------------------------------------------------------------------------------

C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):

[2/162] feature=ts_idx | type=categorical | missing=0.0000 | unique_non_null=8,784
    MI done in 54.4s | mi_score=0.012063
      probe finished for ts_idx in 2.3s | R2=-0.005557 | RMSE=2482.174349
    feature finished in 56.9s | elapsed total 74.8s
--------------------------------------------------------------------------------

C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):

[3/162] feature=pair_id | type=categorical | missing=0.0000 | unique_non_null=2,329
    MI done in 20.0s | mi_score=2.067205
      probe finished for pair_id in 2.1s | R2=0.591166 | RMSE=1582.713967
    feature finished in 22.4s | elapsed total 97.2s
--------------------------------------------------------------------------------
[4/162] feature=primary_use | type=categorical | missing=0.0000 | unique_non_null=16
    MI done in 7.7s | mi_score=0.000000
      probe finished for primary_use in 2.2s | R2=0.013635 | RMSE=2458.372531
    feature finished in 10.2s | elapsed total 107.4s
--------------------------------------------------------------------------------
[5/162] feature=square_feet | type=numeric | missing=0.0000 | unique_non_null=1,376
    MI done in 10.6s | mi_score=1.960127
      probe finished for square_feet in 2.4s | R2=0.024631 | RMSE=2444.631567
    feature finished in 13.1s | elapsed total 120.5s
--------------------------------------------------------------------------------
[6/162] feature=year_built | type=numeric | missing=0.6085 | unique_non_null=116
    MI done in 14.3s | mi_score=0.516757
      probe finished for year_built in 2.3s | R2=0.003129 | RMSE=2471.429647
    feature finished in 16.7s | elapsed total 137.2s
--------------------------------------------------------------------------------
[7/162] feature=floor_count | type=numeric | missing=0.8257 | unique_non_null=18
    MI done in 17.3s | mi_score=0.327342
      probe finished for floor_count in 2.2s | R2=0.002323 | RMSE=2472.429271
    feature finished in 19.6s | elapsed total 156.8s
--------------------------------------------------------------------------------
[8/162] feature=timestamp_gmt | type=categorical | missing=0.0000 | unique_non_null=8,784

C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):

    MI done in 58.0s | mi_score=0.011276
      probe finished for timestamp_gmt in 12.2s | R2=-0.005466 | RMSE=2482.061845
    feature finished in 70.2s | elapsed total 227.1s
--------------------------------------------------------------------------------
[9/162] feature=time_diff_hours | type=numeric | missing=0.0000 | unique_non_null=4
    MI done in 12.4s | mi_score=0.488404
      probe finished for time_diff_hours in 2.2s | R2=0.008256 | RMSE=2465.066835
    feature finished in 14.7s | elapsed total 241.8s
--------------------------------------------------------------------------------
[10/162] feature=air_temperature | type=numeric | missing=0.0000 | unique_non_null=1,014
    MI done in 12.7s | mi_score=0.199694
      probe finished for air_temperature in 2.3s | R2=0.004909 | RMSE=2469.222448
    feature finished in 15.1s | elapsed total 256.9s
--------------------------------------------------------------------------------
[11/162] feature=cloud_coverage | type=numeric | missing=0.0235 | unique_non_null=10
    MI done in 14.6s | mi_score=0.237517
      probe finished for cloud_coverage in 2.3s | R2=0.001947 | RMSE=2472.895064
    feature finished in 16.9s | elapsed total 273.8s
--------------------------------------------------------------------------------
[12/162] feature=dew_temperature | type=numeric | missing=0.0000 | unique_non_null=921
    MI done in 23.2s | mi_score=0.212727
      probe finished for dew_temperature in 4.4s | R2=0.003928 | RMSE=2470.439941
    feature finished in 27.7s | elapsed total 301.6s
--------------------------------------------------------------------------------
[13/162] feature=precip_depth_1_hr | type=numeric | missing=0.0000 | unique_non_null=127
    MI done in 21.3s | mi_score=0.086847
      probe finished for precip_depth_1_hr in 2.3s | R2=0.000020 | RMSE=2475.280893
    feature finished in 23.7s | elapsed total 325.3s
--------------------------------------------------------------------------------
[14/162] feature=sea_level_pressure | type=numeric | missing=0.0394 | unique_non_null=1,770
    MI done in 12.7s | mi_score=0.149076
      probe finished for sea_level_pressure in 2.3s | R2=0.001201 | RMSE=2473.819314
    feature finished in 15.1s | elapsed total 340.4s
--------------------------------------------------------------------------------
[15/162] feature=wind_direction | type=numeric | missing=0.0000 | unique_non_null=43
    MI done in 15.4s | mi_score=0.163221
      probe finished for wind_direction in 2.3s | R2=0.000268 | RMSE=2474.974343
    feature finished in 17.9s | elapsed total 358.3s
--------------------------------------------------------------------------------
[16/162] feature=wind_speed | type=numeric | missing=0.0000 | unique_non_null=335
    MI done in 16.5s | mi_score=0.163593
      probe finished for wind_speed in 2.3s | R2=0.000337 | RMSE=2474.889189
    feature finished in 18.9s | elapsed total 377.2s
--------------------------------------------------------------------------------
[17/162] feature=is_na_holiday | type=boolean | missing=0.0000 | unique_non_null=2
    MI done in 10.0s | mi_score=0.000000
      probe finished for is_na_holiday in 4.2s | R2=0.000001 | RMSE=2475.304426
    feature finished in 14.4s | elapsed total 391.6s
--------------------------------------------------------------------------------
[18/162] feature=is_eu_holiday | type=boolean | missing=0.0000 | unique_non_null=2
    MI done in 10.0s | mi_score=0.000000
      probe finished for is_eu_holiday in 4.3s | R2=0.000000 | RMSE=2475.305537
    feature finished in 14.3s | elapsed total 405.9s
--------------------------------------------------------------------------------
[19/162] feature=hour_sin | type=numeric | missing=0.0000 | unique_non_null=14
    MI done in 18.1s | mi_score=0.143374
      probe finished for hour_sin in 2.3s | R2=0.000017 | RMSE=2475.285135
    feature finished in 20.5s | elapsed total 426.5s
--------------------------------------------------------------------------------
[20/162] feature=hour_cos | type=numeric | missing=0.0000 | unique_non_null=14
    MI done in 17.9s | mi_score=0.145468
      probe finished for hour_cos in 2.3s | R2=0.000150 | RMSE=2475.120704
    feature finished in 20.3s | elapsed total 446.8s
--------------------------------------------------------------------------------
[21/162] feature=dayofweek | type=numeric | missing=0.0000 | unique_non_null=7
    MI done in 15.9s | mi_score=0.153863
      probe finished for dayofweek in 2.3s | R2=0.000047 | RMSE=2475.247462
    feature finished in 18.2s | elapsed total 465.0s
--------------------------------------------------------------------------------
[22/162] feature=doy_sin | type=numeric | missing=0.0000 | unique_non_null=366
    MI done in 9.9s | mi_score=0.145401
      probe finished for doy_sin in 2.3s | R2=0.000161 | RMSE=2475.106462
    feature finished in 12.3s | elapsed total 477.3s
--------------------------------------------------------------------------------
[23/162] feature=doy_cos | type=numeric | missing=0.0000 | unique_non_null=366
    MI done in 9.9s | mi_score=0.145523
      probe finished for doy_cos in 2.3s | R2=0.000319 | RMSE=2474.910705
    feature finished in 12.2s | elapsed total 489.5s
--------------------------------------------------------------------------------
[24/162] feature=is_weekend | type=boolean | missing=0.0000 | unique_non_null=2
    MI done in 9.1s | mi_score=0.000000
      probe finished for is_weekend in 4.2s | R2=0.000054 | RMSE=2475.239180
    feature finished in 13.4s | elapsed total 502.9s
--------------------------------------------------------------------------------
[25/162] feature=is_holiday_any | type=boolean | missing=0.0000 | unique_non_null=2
    MI done in 10.0s | mi_score=0.000000
      probe finished for is_holiday_any in 4.2s | R2=0.000001 | RMSE=2475.304729
    feature finished in 14.3s | elapsed total 517.2s
--------------------------------------------------------------------------------
[26/162] feature=is_business_hours | type=boolean | missing=0.0000 | unique_non_null=2
    MI done in 9.0s | mi_score=0.000000
      probe finished for is_business_hours in 4.2s | R2=0.000187 | RMSE=2475.073837
    feature finished in 13.3s | elapsed total 530.5s
--------------------------------------------------------------------------------
[27/162] feature=CDH_18C | type=numeric | missing=0.0000 | unique_non_null=262
    MI done in 12.6s | mi_score=0.156520
      probe finished for CDH_18C in 2.3s | R2=0.000123 | RMSE=2475.153127
    feature finished in 15.0s | elapsed total 545.5s
--------------------------------------------------------------------------------
[28/162] feature=HDH_18C | type=numeric | missing=0.0000 | unique_non_null=741
    MI done in 12.7s | mi_score=0.207862
      probe finished for HDH_18C in 2.3s | R2=0.008322 | RMSE=2464.985193
    feature finished in 15.2s | elapsed total 560.7s
--------------------------------------------------------------------------------
[29/162] feature=is_hot_24C | type=boolean | missing=0.0000 | unique_non_null=2
    MI done in 9.1s | mi_score=0.000000
      probe finished for is_hot_24C in 4.2s | R2=0.000075 | RMSE=2475.213122
    feature finished in 13.5s | elapsed total 574.1s
--------------------------------------------------------------------------------
[30/162] feature=is_cold_10C | type=boolean | missing=0.0000 | unique_non_null=2
    MI done in 9.1s | mi_score=0.000000
      probe finished for is_cold_10C in 4.3s | R2=0.002383 | RMSE=2472.354647
    feature finished in 13.5s | elapsed total 587.6s
--------------------------------------------------------------------------------
[31/162] feature=dewpoint_depression | type=numeric | missing=0.0000 | unique_non_null=1,384
    MI done in 13.8s | mi_score=0.198369
      probe finished for dewpoint_depression in 2.3s | R2=0.001376 | RMSE=2473.602636
    feature finished in 16.2s | elapsed total 603.9s
--------------------------------------------------------------------------------
[32/162] feature=log_sqft | type=numeric | missing=0.0000 | unique_non_null=1,376
    MI done in 10.4s | mi_score=1.965561
      probe finished for log_sqft in 2.4s | R2=0.043847 | RMSE=2420.430334
    feature finished in 12.9s | elapsed total 616.8s
--------------------------------------------------------------------------------
[33/162] feature=year_built_clipped | type=numeric | missing=0.6085 | unique_non_null=116
    MI done in 14.2s | mi_score=0.516757
      probe finished for year_built_clipped in 2.3s | R2=0.003129 | RMSE=2471.429647
    feature finished in 16.6s | elapsed total 633.4s
--------------------------------------------------------------------------------
[34/162] feature=site_id | type=categorical | missing=0.0000 | unique_non_null=16

C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):

    MI done in 7.8s | mi_score=0.000000
      probe finished for site_id in 2.0s | R2=0.025531 | RMSE=2443.503121
    feature finished in 10.0s | elapsed total 643.4s
--------------------------------------------------------------------------------

C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):

[35/162] feature=meter | type=categorical | missing=0.0000 | unique_non_null=4
    MI done in 8.5s | mi_score=0.000000
      probe finished for meter in 1.8s | R2=0.034263 | RMSE=2432.530678
    feature finished in 10.5s | elapsed total 653.9s
--------------------------------------------------------------------------------
[36/162] feature=thermal_heat_stress | type=numeric | missing=0.0000 | unique_non_null=636,032
    MI done in 12.0s | mi_score=0.170150
      probe finished for thermal_heat_stress in 2.4s | R2=0.011318 | RMSE=2461.258621
    feature finished in 14.6s | elapsed total 668.4s
--------------------------------------------------------------------------------
[37/162] feature=thermal_cool_stress | type=numeric | missing=0.0000 | unique_non_null=413,953
    MI done in 12.0s | mi_score=0.168196
      probe finished for thermal_cool_stress in 2.4s | R2=0.003274 | RMSE=2471.250089
    feature finished in 14.6s | elapsed total 683.0s
--------------------------------------------------------------------------------
[38/162] feature=moisture_infiltration_stress | type=numeric | missing=0.0000 | unique_non_null=257,959
    MI done in 12.6s | mi_score=0.160980
      probe finished for moisture_infiltration_stress in 2.3s | R2=0.000502 | RMSE=2474.684222
    feature finished in 15.0s | elapsed total 698.0s
--------------------------------------------------------------------------------
[39/162] feature=thermal_memory_shock | type=numeric | missing=0.0000 | unique_non_null=1,862,595
    MI done in 13.3s | mi_score=0.008812
      probe finished for thermal_memory_shock in 2.4s | R2=0.000445 | RMSE=2474.755240
    feature finished in 16.1s | elapsed total 714.1s
--------------------------------------------------------------------------------
[40/162] feature=wx_cooling_response | type=numeric | missing=0.0000 | unique_non_null=1,525,434
    MI done in 10.9s | mi_score=0.283047
      probe finished for wx_cooling_response in 2.4s | R2=0.000594 | RMSE=2474.570468
    feature finished in 13.5s | elapsed total 727.6s
--------------------------------------------------------------------------------
[41/162] feature=wx_heating_response | type=numeric | missing=0.0000 | unique_non_null=1,135,408
    MI done in 10.8s | mi_score=0.201768
      probe finished for wx_heating_response in 2.4s | R2=0.006794 | RMSE=2466.882446
    feature finished in 13.5s | elapsed total 741.1s
--------------------------------------------------------------------------------
[42/162] feature=wx_latent_response | type=numeric | missing=0.0000 | unique_non_null=1,875,357
    MI done in 11.0s | mi_score=0.088745
      probe finished for wx_latent_response in 2.4s | R2=0.000586 | RMSE=2474.580267
    feature finished in 13.8s | elapsed total 754.8s
--------------------------------------------------------------------------------
[43/162] feature=wx_envelope_response | type=numeric | missing=0.0000 | unique_non_null=1,412,217
    MI done in 12.0s | mi_score=0.068766
      probe finished for wx_envelope_response in 2.4s | R2=0.002942 | RMSE=2471.661991
    feature finished in 14.6s | elapsed total 769.4s
--------------------------------------------------------------------------------
[44/162] feature=meta_missing_score | type=numeric | missing=0.0000 | unique_non_null=3
    MI done in 12.9s | mi_score=0.347407
      probe finished for meta_missing_score in 0.3s | R2=0.003032 | RMSE=2471.550323
    feature finished in 13.3s | elapsed total 782.8s
--------------------------------------------------------------------------------
[45/162] feature=weather_implausibility_score | type=numeric | missing=0.0000 | unique_non_null=14
    MI done in 15.3s | mi_score=0.087374
      probe finished for weather_implausibility_score in 2.3s | R2=0.000004 | RMSE=2475.300285
    feature finished in 17.7s | elapsed total 800.5s
--------------------------------------------------------------------------------
[46/162] feature=contextual_weather_anomaly | type=numeric | missing=0.0000 | unique_non_null=269,057
    MI done in 10.8s | mi_score=0.068068
      probe finished for contextual_weather_anomaly in 2.4s | R2=0.002086 | RMSE=2472.722184
    feature finished in 13.3s | elapsed total 813.8s
--------------------------------------------------------------------------------
[47/162] feature=contextual_structure_anomaly | type=numeric | missing=0.0000 | unique_non_null=1,396
    MI done in 10.5s | mi_score=1.944688
      probe finished for contextual_structure_anomaly in 2.4s | R2=0.001070 | RMSE=2473.981710
    feature finished in 13.0s | elapsed total 826.9s
--------------------------------------------------------------------------------
[48/162] feature=bp_heat_drive | type=numeric | missing=0.0000 | unique_non_null=1,134,721
    MI done in 11.1s | mi_score=0.117550
      probe finished for bp_heat_drive in 2.4s | R2=0.008235 | RMSE=2465.092696
    feature finished in 13.7s | elapsed total 840.6s
--------------------------------------------------------------------------------
[49/162] feature=bp_cool_drive | type=numeric | missing=0.0000 | unique_non_null=214,954
    MI done in 10.7s | mi_score=0.624642
      probe finished for bp_cool_drive in 2.4s | R2=0.002130 | RMSE=2472.668296
    feature finished in 13.2s | elapsed total 853.7s
--------------------------------------------------------------------------------
[50/162] feature=bp_latent_drive | type=numeric | missing=0.0000 | unique_non_null=1,890,764
    MI done in 10.9s | mi_score=0.075617
      probe finished for bp_latent_drive in 2.4s | R2=0.000695 | RMSE=2474.445493
    feature finished in 13.7s | elapsed total 867.5s
--------------------------------------------------------------------------------
[51/162] feature=bp_thermal_position | type=numeric | missing=0.0000 | unique_non_null=12,124
    MI done in 10.8s | mi_score=0.489551
      probe finished for bp_thermal_position in 2.3s | R2=0.008793 | RMSE=2464.399623
    feature finished in 13.2s | elapsed total 880.7s
--------------------------------------------------------------------------------
[52/162] feature=r2_air_temperature_site_mean | type=numeric | missing=0.0000 | unique_non_null=16
    MI done in 10.9s | mi_score=1.003964
      probe finished for r2_air_temperature_site_mean in 2.3s | R2=0.009668 | RMSE=2463.310679
    feature finished in 13.4s | elapsed total 894.0s
--------------------------------------------------------------------------------
[53/162] feature=r2_air_temperature_site_std | type=numeric | missing=0.0000 | unique_non_null=16
    MI done in 11.2s | mi_score=1.004720
      probe finished for r2_air_temperature_site_std in 2.3s | R2=0.019637 | RMSE=2450.881576
    feature finished in 13.7s | elapsed total 907.7s
--------------------------------------------------------------------------------
[54/162] feature=r2_air_temperature_site_z | type=numeric | missing=0.0000 | unique_non_null=3,321
    MI done in 10.2s | mi_score=0.449112
      probe finished for r2_air_temperature_site_z in 2.3s | R2=0.000098 | RMSE=2475.184640
    feature finished in 12.7s | elapsed total 920.3s
--------------------------------------------------------------------------------
[55/162] feature=r2_air_temperature_site_pos | type=numeric | missing=0.0000 | unique_non_null=2,596
    MI done in 10.1s | mi_score=0.442352
      probe finished for r2_air_temperature_site_pos in 2.3s | R2=0.000651 | RMSE=2474.500455
    feature finished in 12.5s | elapsed total 932.9s
--------------------------------------------------------------------------------
[56/162] feature=r2_dew_temperature_site_mean | type=numeric | missing=0.0000 | unique_non_null=16
    MI done in 11.2s | mi_score=1.003119
      probe finished for r2_dew_temperature_site_mean in 2.3s | R2=0.009893 | RMSE=2463.031161
    feature finished in 13.6s | elapsed total 946.5s
--------------------------------------------------------------------------------
[57/162] feature=r2_dew_temperature_site_std | type=numeric | missing=0.0000 | unique_non_null=16
    MI done in 11.0s | mi_score=1.004609
      probe finished for r2_dew_temperature_site_std in 2.3s | R2=0.015260 | RMSE=2456.346881
    feature finished in 13.4s | elapsed total 959.9s
--------------------------------------------------------------------------------
[58/162] feature=r2_dew_temperature_site_z | type=numeric | missing=0.0000 | unique_non_null=2,988
    MI done in 9.9s | mi_score=0.462969
      probe finished for r2_dew_temperature_site_z in 2.3s | R2=0.000750 | RMSE=2474.377497
    feature finished in 12.3s | elapsed total 972.2s
--------------------------------------------------------------------------------
[59/162] feature=r2_dew_temperature_site_pos | type=numeric | missing=0.0000 | unique_non_null=2,247
    MI done in 10.1s | mi_score=0.439814
      probe finished for r2_dew_temperature_site_pos in 2.3s | R2=0.000725 | RMSE=2474.408313
    feature finished in 12.5s | elapsed total 984.7s
--------------------------------------------------------------------------------
[60/162] feature=r2_sea_level_pressure_site_mean | type=numeric | missing=0.0000 | unique_non_null=16
    MI done in 11.1s | mi_score=0.991783
      probe finished for r2_sea_level_pressure_site_mean in 2.3s | R2=0.009606 | RMSE=2463.387607
    feature finished in 13.5s | elapsed total 998.2s
--------------------------------------------------------------------------------
[61/162] feature=r2_sea_level_pressure_site_std | type=numeric | missing=0.0000 | unique_non_null=16
    MI done in 11.0s | mi_score=1.004818
      probe finished for r2_sea_level_pressure_site_std in 2.3s | R2=0.013869 | RMSE=2458.081061
    feature finished in 13.4s | elapsed total 1011.7s
--------------------------------------------------------------------------------
[62/162] feature=r2_sea_level_pressure_site_z | type=numeric | missing=0.0000 | unique_non_null=7,891
    MI done in 10.6s | mi_score=0.291660
      probe finished for r2_sea_level_pressure_site_z in 2.4s | R2=0.000016 | RMSE=2475.286448
    feature finished in 13.1s | elapsed total 1024.8s
--------------------------------------------------------------------------------
[63/162] feature=r2_sea_level_pressure_site_pos | type=numeric | missing=0.0000 | unique_non_null=7,285
    MI done in 10.4s | mi_score=0.291632
      probe finished for r2_sea_level_pressure_site_pos in 2.4s | R2=0.000566 | RMSE=2474.604918
    feature finished in 12.9s | elapsed total 1037.7s
--------------------------------------------------------------------------------
[64/162] feature=r2_wind_speed_site_mean | type=numeric | missing=0.0000 | unique_non_null=16
    MI done in 11.4s | mi_score=1.004774
      probe finished for r2_wind_speed_site_mean in 2.3s | R2=0.002432 | RMSE=2472.293470
    feature finished in 13.8s | elapsed total 1051.5s
--------------------------------------------------------------------------------
[65/162] feature=r2_wind_speed_site_std | type=numeric | missing=0.0000 | unique_non_null=16
    MI done in 11.4s | mi_score=1.005056
      probe finished for r2_wind_speed_site_std in 2.3s | R2=0.002195 | RMSE=2472.587612
    feature finished in 13.8s | elapsed total 1065.3s
--------------------------------------------------------------------------------
[66/162] feature=r2_wind_speed_site_z | type=numeric | missing=0.0000 | unique_non_null=987
    MI done in 10.9s | mi_score=0.603449
      probe finished for r2_wind_speed_site_z in 2.3s | R2=0.000031 | RMSE=2475.267864
    feature finished in 13.3s | elapsed total 1078.7s
--------------------------------------------------------------------------------
[67/162] feature=r2_wind_speed_site_pos | type=numeric | missing=0.0000 | unique_non_null=700
    MI done in 11.8s | mi_score=0.471852
      probe finished for r2_wind_speed_site_pos in 2.4s | R2=0.000363 | RMSE=2474.856663
    feature finished in 14.3s | elapsed total 1093.0s
--------------------------------------------------------------------------------
[68/162] feature=r2_cloud_coverage_site_mean | type=numeric | missing=0.0000 | unique_non_null=15
    MI done in 11.4s | mi_score=0.998174
      probe finished for r2_cloud_coverage_site_mean in 2.3s | R2=0.001960 | RMSE=2472.878990
    feature finished in 13.8s | elapsed total 1106.8s
--------------------------------------------------------------------------------
[69/162] feature=r2_cloud_coverage_site_std | type=numeric | missing=0.0000 | unique_non_null=15
    MI done in 11.1s | mi_score=1.000198
      probe finished for r2_cloud_coverage_site_std in 2.3s | R2=0.018509 | RMSE=2452.290766
    feature finished in 13.5s | elapsed total 1120.2s
--------------------------------------------------------------------------------
[70/162] feature=r2_cloud_coverage_site_z | type=numeric | missing=0.0000 | unique_non_null=68
    MI done in 11.3s | mi_score=0.829102
      probe finished for r2_cloud_coverage_site_z in 2.3s | R2=0.000113 | RMSE=2475.165752
    feature finished in 13.7s | elapsed total 1133.9s
--------------------------------------------------------------------------------
[71/162] feature=r2_cloud_coverage_site_pos | type=numeric | missing=0.0000 | unique_non_null=14
    MI done in 14.8s | mi_score=0.252975
      probe finished for r2_cloud_coverage_site_pos in 2.2s | R2=0.000970 | RMSE=2474.104889
    feature finished in 17.1s | elapsed total 1151.0s
--------------------------------------------------------------------------------
[72/162] feature=r2_precip_depth_1_hr_site_mean | type=numeric | missing=0.0000 | unique_non_null=14
    MI done in 11.0s | mi_score=0.963540
      probe finished for r2_precip_depth_1_hr_site_mean in 2.2s | R2=0.015112 | RMSE=2456.531193
    feature finished in 13.3s | elapsed total 1164.3s
--------------------------------------------------------------------------------
[73/162] feature=r2_precip_depth_1_hr_site_std | type=numeric | missing=0.0000 | unique_non_null=14
    MI done in 11.0s | mi_score=0.964122
      probe finished for r2_precip_depth_1_hr_site_std in 2.3s | R2=0.005216 | RMSE=2468.842036
    feature finished in 13.4s | elapsed total 1177.7s
--------------------------------------------------------------------------------
[74/162] feature=r2_precip_depth_1_hr_site_z | type=numeric | missing=0.0000 | unique_non_null=596
    MI done in 10.6s | mi_score=0.918554
      probe finished for r2_precip_depth_1_hr_site_z in 2.3s | R2=0.000054 | RMSE=2475.238372
    feature finished in 13.0s | elapsed total 1190.8s
--------------------------------------------------------------------------------
[75/162] feature=r2_precip_depth_1_hr_site_pos | type=numeric | missing=0.0000 | unique_non_null=418
    MI done in 16.7s | mi_score=0.091778
      probe finished for r2_precip_depth_1_hr_site_pos in 2.3s | R2=0.000017 | RMSE=2475.285337
    feature finished in 19.1s | elapsed total 1209.8s
--------------------------------------------------------------------------------
[76/162] feature=r4_air_temperature_sitehour_mean | type=numeric | missing=0.0000 | unique_non_null=361
    MI done in 10.9s | mi_score=0.543695
      probe finished for r4_air_temperature_sitehour_mean in 2.3s | R2=0.005049 | RMSE=2469.049615
    feature finished in 13.3s | elapsed total 1223.1s
--------------------------------------------------------------------------------
[77/162] feature=r4_air_temperature_sitehour_std | type=numeric | missing=0.0000 | unique_non_null=361
    MI done in 10.7s | mi_score=0.546215
      probe finished for r4_air_temperature_sitehour_std in 2.3s | R2=0.016311 | RMSE=2455.035132
    feature finished in 13.1s | elapsed total 1236.3s
--------------------------------------------------------------------------------
[78/162] feature=r4_dew_temperature_sitehour_mean | type=numeric | missing=0.0000 | unique_non_null=361
    MI done in 10.5s | mi_score=0.552165
      probe finished for r4_dew_temperature_sitehour_mean in 2.3s | R2=0.008750 | RMSE=2464.452272
    feature finished in 12.9s | elapsed total 1249.2s
--------------------------------------------------------------------------------
[79/162] feature=r4_dew_temperature_sitehour_std | type=numeric | missing=0.0000 | unique_non_null=361
    MI done in 10.6s | mi_score=0.545358
      probe finished for r4_dew_temperature_sitehour_std in 2.3s | R2=0.014906 | RMSE=2456.788554
    feature finished in 13.0s | elapsed total 1262.2s
--------------------------------------------------------------------------------
[80/162] feature=r4_sea_level_pressure_sitehour_mean | type=numeric | missing=0.0000 | unique_non_null=338
    MI done in 10.6s | mi_score=0.550325
      probe finished for r4_sea_level_pressure_sitehour_mean in 2.3s | R2=0.004301 | RMSE=2469.977125
    feature finished in 13.0s | elapsed total 1275.2s
--------------------------------------------------------------------------------
[81/162] feature=r4_sea_level_pressure_sitehour_std | type=numeric | missing=0.0000 | unique_non_null=338
    MI done in 10.2s | mi_score=0.559271
      probe finished for r4_sea_level_pressure_sitehour_std in 2.3s | R2=0.009270 | RMSE=2463.806608
    feature finished in 12.7s | elapsed total 1287.9s
--------------------------------------------------------------------------------
[82/162] feature=r4_wind_speed_sitehour_mean | type=numeric | missing=0.0000 | unique_non_null=361
    MI done in 10.6s | mi_score=0.542365
      probe finished for r4_wind_speed_sitehour_mean in 2.3s | R2=0.001661 | RMSE=2473.248875
    feature finished in 13.0s | elapsed total 1300.9s
--------------------------------------------------------------------------------
[83/162] feature=r4_wind_speed_sitehour_std | type=numeric | missing=0.0000 | unique_non_null=361
    MI done in 10.4s | mi_score=0.540683
      probe finished for r4_wind_speed_sitehour_std in 2.3s | R2=0.001571 | RMSE=2473.361074
    feature finished in 12.9s | elapsed total 1313.8s
--------------------------------------------------------------------------------
[84/162] feature=r4_cloud_coverage_sitehour_mean | type=numeric | missing=0.0000 | unique_non_null=281
    MI done in 14.9s | mi_score=0.560560
      probe finished for r4_cloud_coverage_sitehour_mean in 4.1s | R2=0.002072 | RMSE=2472.740282
    feature finished in 19.1s | elapsed total 1332.9s
--------------------------------------------------------------------------------
[85/162] feature=r4_cloud_coverage_sitehour_std | type=numeric | missing=0.0000 | unique_non_null=302
    MI done in 23.7s | mi_score=0.567052
      probe finished for r4_cloud_coverage_sitehour_std in 4.0s | R2=0.006658 | RMSE=2467.051783
    feature finished in 27.9s | elapsed total 1360.8s
--------------------------------------------------------------------------------
[86/162] feature=r4_precip_depth_1_hr_sitehour_mean | type=numeric | missing=0.0000 | unique_non_null=253
    MI done in 25.3s | mi_score=0.522190
      probe finished for r4_precip_depth_1_hr_sitehour_mean in 4.2s | R2=0.004657 | RMSE=2469.535280
    feature finished in 29.7s | elapsed total 1390.5s
--------------------------------------------------------------------------------
[87/162] feature=r4_precip_depth_1_hr_sitehour_std | type=numeric | missing=0.0000 | unique_non_null=290
    MI done in 23.1s | mi_score=0.534813
      probe finished for r4_precip_depth_1_hr_sitehour_std in 4.3s | R2=0.001186 | RMSE=2473.837606
    feature finished in 27.5s | elapsed total 1418.0s
--------------------------------------------------------------------------------
[88/162] feature=r4_air_temperature_sitehour_z | type=numeric | missing=0.0000 | unique_non_null=31,501
    MI done in 24.3s | mi_score=0.137378
      probe finished for r4_air_temperature_sitehour_z in 4.2s | R2=0.000168 | RMSE=2475.097372
    feature finished in 28.8s | elapsed total 1446.8s
--------------------------------------------------------------------------------
[89/162] feature=r4_dew_temperature_sitehour_z | type=numeric | missing=0.0000 | unique_non_null=30,967
    MI done in 23.5s | mi_score=0.140657

,feature,feature_group,source_ablation_group,feature_type,missing_rate,n_unique_non_null,mi_score,probe_cv_r2,probe_cv_rmse,probe_model,n_rows_used
0,pair_id,base,base,categorical,0.0,2329,2.067205,0.591166,1582.713967,categorical_factor_ridge_sparse,2000000
1,building_id,base,base,categorical,0.0,1425,1.629829,0.265496,2121.416154,categorical_factor_ridge_sparse,2000000
2,log_sqft,base,base,numeric,0.0,1376,1.965561,0.043847,2420.430334,natural_cubic_spline_df4,2000000
3,meter,base,base,categorical,0.0,4,0.000000,0.034263,2432.530678,categorical_factor_ridge_sparse,2000000
4,site_id,base,base,categorical,0.0,16,0.000000,0.025531,2443.503121,categorical_factor_ridge_sparse,2000000
...,...,...,...,...,...,...,...,...,...,...,...
157,r5_local_hour,rank5,rank5,numeric,0.0,24,0.135001,0.000146,2475.125249,natural_cubic_spline_df4,2000000
158,r5_frac_primary_use_dayofyear,rank5,rank5,numeric,0.0,5330,0.200675,0.000115,2475.162924,natural_cubic_spline_df4,2000000
159,r5_is_day_off_or_holiday,rank5,rank5,boolean,0.0,2,0.000000,0.000052,2475.241200,boolean_factor_ridge_sparse,2000000
160,r5_is_weekend_local,rank5,rank5,boolean,0.0,2,0.000000,0.000051,2475.243018,boolean_factor_ridge_sparse,2000000
161,r5_local_weekday,rank5,rank5,numeric,0.0,7,0.150884,0.000045,2475.250492,natural_cubic_spline_df4,2000000

In [14]:
per_feature_results.to_csv("per_feature_quality_dependency_results.csv", index=False)

## Whole-set probe for baseline and baseline + each supplementary feature group

Old two-group setup is retained in the following code cell as comments; the revised version evaluates baseline plus expert, rank2, rank4, rank5, and rank25.

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

In [16]:
def _make_sparse_onehot_encoder(min_frequency=None, dtype=np.float32):
    kwargs = {
        "handle_unknown": "ignore",
        "dtype": dtype,
    }
    if min_frequency is not None:
        kwargs["min_frequency"] = min_frequency

    try:
        return OneHotEncoder(sparse_output=True, **kwargs)
    except TypeError:
        return OneHotEncoder(sparse=True, **kwargs)


def prepare_feature_set_frame(df_in: pd.DataFrame, feature_cols):
    """
    Prepare a mixed-type feature frame for the whole-set probe.
    - numeric -> numeric with NaN preserved for later median imputation
    - boolean/categorical -> string categories with '__MISSING__' filled in
    """
    X = df_in.loc[:, feature_cols].copy()

    type_map = {}
    numeric_cols = []
    discrete_cols = []

    for col in feature_cols:
        feature_type = infer_feature_type(X[col])
        type_map[col] = feature_type

        if feature_type == "numeric":
            X[col] = pd.to_numeric(X[col], errors="coerce")
            numeric_cols.append(col)

        elif feature_type == "boolean":
            X[col] = normalize_boolean_series(X[col]).astype("object").where(X[col].notna(), "__MISSING__").astype(str)
            discrete_cols.append(col)

        else:  # categorical
            X[col] = X[col].astype("object").where(X[col].notna(), "__MISSING__").astype(str)
            discrete_cols.append(col)

    return X, type_map, numeric_cols, discrete_cols


def make_feature_set_preprocessor(numeric_cols, discrete_cols, min_frequency=None):
    """
    Whole-set preprocessing:
    - numeric: median imputation
    - boolean/categorical: one-hot encoding
    """
    transformers = []

    if len(numeric_cols) > 0:
        transformers.append(
            (
                "num",
                Pipeline(
                    steps=[
                        ("imputer", SimpleImputer(strategy="median")),
                    ]
                ),
                numeric_cols,
            )
        )

    if len(discrete_cols) > 0:
        transformers.append(
            (
                "disc",
                _make_sparse_onehot_encoder(min_frequency=min_frequency),
                discrete_cols,
            )
        )

    return ColumnTransformer(
        transformers=transformers,
        remainder="drop",
        sparse_threshold=1.0,
    )

In [17]:
def evaluate_feature_set_probe(
    feature_cols,
    target_col,
    sample_size=None,
    n_splits=3,
    random_state=42,
    ridge_alpha=1.0,
    min_frequency=None,
):
    """
    Evaluate a whole feature set against the numeric target using a weak multivariate probe.

    Parameters
    ----------
    feature_cols : list[str]
        Feature columns to include.
    target_col : str
        Numeric target column.
    sample_size : int or None
        Optional row subsample for speed. If None, use all valid rows.
    n_splits : int
        CV folds. 3 is a good default for very large data.
    ridge_alpha : float
        Ridge regularization strength.
    min_frequency : int/float/None
        Optional OneHotEncoder infrequent-category grouping threshold.
        Leave as None unless cardinality becomes a runtime/memory issue.

    Returns
    -------
    dict
    """
    y_all = pd.to_numeric(df_full[target_col], errors="coerce")
    valid_mask = y_all.notna()

    X_raw = df_full.loc[valid_mask, feature_cols]
    y = y_all.loc[valid_mask]
    print(X_raw.head(5))

    # Optional subsample for speed
    if sample_size is not None and len(X_raw) > sample_size:
        sampled_idx = X_raw.sample(n=sample_size, random_state=random_state).index
        X_raw = X_raw.loc[sampled_idx]
        y = y.loc[sampled_idx]

    X_raw = X_raw.reset_index(drop=True)
    y = y.reset_index(drop=True)

    if len(y) < 2:
        return {
            "set_name": None,
            "n_rows_used": int(len(y)),
            "n_input_features": int(len(feature_cols)),
            "n_numeric_features": np.nan,
            "n_discrete_features": np.nan,
            "set_cv_r2": np.nan,
            "set_cv_rmse": np.nan,
            "ridge_alpha": ridge_alpha,
            "n_splits": n_splits,
            "sample_size": sample_size,
        }

    X, type_map, numeric_cols, discrete_cols = prepare_feature_set_frame(X_raw, feature_cols)

    preprocessor = make_feature_set_preprocessor(
        numeric_cols=numeric_cols,
        discrete_cols=discrete_cols,
        min_frequency=min_frequency,
    )

    model = Pipeline(
        steps=[
            ("prep", preprocessor),
            ("reg", Ridge(alpha=ridge_alpha, solver="lsqr")),
        ]
    )

    n_splits_eff = min(n_splits, len(y))
    if n_splits_eff < 2:
        return {
            "set_name": None,
            "n_rows_used": int(len(y)),
            "n_input_features": int(len(feature_cols)),
            "n_numeric_features": int(len(numeric_cols)),
            "n_discrete_features": int(len(discrete_cols)),
            "set_cv_r2": np.nan,
            "set_cv_rmse": np.nan,
            "ridge_alpha": ridge_alpha,
            "n_splits": n_splits_eff,
            "sample_size": sample_size,
        }

    cv = KFold(n_splits=n_splits_eff, shuffle=True, random_state=random_state)
    oof_pred = np.full(len(y), np.nan, dtype=float)

    for train_idx, test_idx in cv.split(X):
        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        y_train = y.iloc[train_idx]

        model.fit(X_train, y_train)
        oof_pred[test_idx] = model.predict(X_test)

    set_cv_r2 = r2_score(y, oof_pred)
    set_cv_rmse = np.sqrt(mean_squared_error(y, oof_pred))

    return {
        "set_name": None,
        "n_rows_used": int(len(y)),
        "n_input_features": int(len(feature_cols)),
        "n_numeric_features": int(len(numeric_cols)),
        "n_discrete_features": int(len(discrete_cols)),
        "set_cv_r2": float(set_cv_r2),
        "set_cv_rmse": float(set_cv_rmse),
        "ridge_alpha": ridge_alpha,
        "n_splits": n_splits_eff,
        "sample_size": sample_size,
    }

In [18]:
# Old code retained for reference.
# # You can start smaller for speed, e.g. 500_000 or 1_000_000
# sample_size_for_set_probe = 2_000_000
#
# base_set_stats = evaluate_feature_set_probe(
#     feature_cols=cols_base,
#     target_col=target_col,
#     sample_size=sample_size_for_set_probe,
#     n_splits=3,
#     random_state=42,
#     ridge_alpha=1.0,
#     min_frequency=None,
# )
# base_set_stats["set_name"] = "base_only"
#
# full_feature_cols = list(cols_base) + list(cols_exp)
# full_set_stats = evaluate_feature_set_probe(
#     feature_cols=full_feature_cols,
#     target_col=target_col,
#     sample_size=sample_size_for_set_probe,
#     n_splits=3,
#     random_state=42,
#     ridge_alpha=1.0,
#     min_frequency=None,
# )
# full_set_stats["set_name"] = "base_plus_exp"
#
# feature_set_results = pd.DataFrame([base_set_stats, full_set_stats])
#
# base_r2 = feature_set_results.loc[feature_set_results["set_name"] == "base_only", "set_cv_r2"].iloc[0]
# base_rmse = feature_set_results.loc[feature_set_results["set_name"] == "base_only", "set_cv_rmse"].iloc[0]
#
# feature_set_results["delta_r2_vs_base"] = feature_set_results["set_cv_r2"] - base_r2
# feature_set_results["delta_rmse_vs_base"] = feature_set_results["set_cv_rmse"] - base_rmse
#
# feature_set_results

# Revised: evaluate baseline and baseline + each supplementary feature group.
sample_size_for_set_probe = 2_000_000

probe_group_defs = [
    ("base_only", cols_base),
    ("base_plus_expert", list(cols_base) + list(cols_exp)),
    ("base_plus_rank2", list(cols_base) + list(cols_rank2)),
    ("base_plus_rank4", list(cols_base) + list(cols_rank4)),
    ("base_plus_rank5", list(cols_base) + list(cols_rank5)),
    ("base_plus_rank25", list(cols_base) + list(cols_rank25)),
]

feature_set_rows = []
for set_name, feature_cols in probe_group_defs:
    stats = evaluate_feature_set_probe(
        feature_cols=feature_cols,
        target_col=target_col,
        sample_size=sample_size_for_set_probe,
        n_splits=3,
        random_state=42,
        ridge_alpha=1.0,
        min_frequency=None,
    )
    stats["set_name"] = set_name
    feature_set_rows.append(stats)

feature_set_results = pd.DataFrame(feature_set_rows)

base_r2 = feature_set_results.loc[feature_set_results["set_name"] == "base_only", "set_cv_r2"].iloc[0]
base_rmse = feature_set_results.loc[feature_set_results["set_name"] == "base_only", "set_cv_rmse"].iloc[0]

feature_set_results["delta_r2_vs_base"] = feature_set_results["set_cv_r2"] - base_r2
feature_set_results["delta_rmse_vs_base"] = feature_set_results["set_cv_rmse"] - base_rmse

feature_set_results

  building_id ts_idx pair_id primary_use  square_feet  year_built  \
0           0   3384       0   Education         7432      2008.0
1           1   3384       4   Education         2720      2004.0
2           2   3384       8   Education         5376      1991.0
3           3   3384      12   Education        23685      2002.0
4           4   3384      16   Education       116607      1975.0

   floor_count       timestamp_gmt  time_diff_hours  air_temperature  ...  \
0          NaN 2016-05-21 04:00:00              4.0             25.0  ...
1          NaN 2016-05-21 04:00:00              4.0             25.0  ...
2          NaN 2016-05-21 04:00:00              4.0             25.0  ...
3          NaN 2016-05-21 04:00:00              4.0             25.0  ...
4          NaN 2016-05-21 04:00:00              4.0             25.0  ...

   is_business_hours  CDH_18C  HDH_18C  is_hot_24C  is_cold_10C  \
0                  0      7.0      0.0           1            0
1                  0      7.0      0.0           1            0
2                  0      7.0      0.0           1            0
3                  0      7.0      0.0           1            0
4                  0      7.0      0.0           1            0

   dewpoint_depression   log_sqft  year_built_clipped  site_id  meter
0                  4.4   8.913685              2008.0        0      0
1                  4.4   7.908755              2004.0        0      0
2                  4.4   8.589886              1991.0        0      0
3                  4.4  10.072639              2002.0        0      0
4                  4.4  11.666574              1975.0        0      0

[5 rows x 35 columns]

C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):

  building_id ts_idx pair_id primary_use  square_feet  year_built  \
0           0   3384       0   Education         7432      2008.0
1           1   3384       4   Education         2720      2004.0
2           2   3384       8   Education         5376      1991.0
3           3   3384      12   Education        23685      2002.0
4           4   3384      16   Education       116607      1975.0

   floor_count       timestamp_gmt  time_diff_hours  air_temperature  ...  \
0          NaN 2016-05-21 04:00:00              4.0             25.0  ...
1          NaN 2016-05-21 04:00:00              4.0             25.0  ...
2          NaN 2016-05-21 04:00:00              4.0             25.0  ...
3          NaN 2016-05-21 04:00:00              4.0             25.0  ...
4          NaN 2016-05-21 04:00:00              4.0             25.0  ...

   wx_latent_response  wx_envelope_response  meta_missing_score  \
0            2.859566              1.054335            0.333333
1            2.776042              0.997357            0.333333
2            2.824721              1.030381            0.333333
3            2.975187              1.135654            0.333333
4            3.201219              1.302363            0.333333

   weather_implausibility_score  contextual_weather_anomaly  \
0                           0.0                    0.358323
1                           0.0                    0.358323
2                           0.0                    0.358323
3                           0.0                    0.358323
4                           0.0                    0.358323

   contextual_structure_anomaly  bp_heat_drive  bp_cool_drive  \
0                      0.485191       0.000889       3.650867
1                      0.494842       0.000848       3.515881
2                      0.428898       0.000873       3.598825
3                      0.381946       0.000944       3.837142
4                      0.091664       0.001021       4.093328

   bp_latent_drive  bp_thermal_position
0         1.159452             0.954045
1         1.125833             0.954045
2         1.146490             0.954045
3         1.205844             0.954045
4         1.269649             0.954045

[5 rows x 51 columns]

C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):

  building_id ts_idx pair_id primary_use  square_feet  year_built  \
0           0   3384       0   Education         7432      2008.0
1           1   3384       4   Education         2720      2004.0
2           2   3384       8   Education         5376      1991.0
3           3   3384      12   Education        23685      2002.0
4           4   3384      16   Education       116607      1975.0

   floor_count       timestamp_gmt  time_diff_hours  air_temperature  ...  \
0          NaN 2016-05-21 04:00:00              4.0             25.0  ...
1          NaN 2016-05-21 04:00:00              4.0             25.0  ...
2          NaN 2016-05-21 04:00:00              4.0             25.0  ...
3          NaN 2016-05-21 04:00:00              4.0             25.0  ...
4          NaN 2016-05-21 04:00:00              4.0             25.0  ...

   r2_wind_speed_site_z  r2_wind_speed_site_pos  r2_cloud_coverage_site_mean  \
0             -0.808319                0.097403                     4.183257
1             -0.808319                0.097403                     4.183257
2             -0.808319                0.097403                     4.183257
3             -0.808319                0.097403                     4.183257
4             -0.808319                0.097403                     4.183257

   r2_cloud_coverage_site_std  r2_cloud_coverage_site_z  \
0                    2.256157                  0.805238
1                    2.256157                  0.805238
2                    2.256157                  0.805238
3                    2.256157                  0.805238
4                    2.256157                  0.805238

   r2_cloud_coverage_site_pos  r2_precip_depth_1_hr_site_mean  \
0                    0.666667                        1.541754
1                    0.666667                        1.541754
2                    0.666667                        1.541754
3                    0.666667                        1.541754
4                    0.666667                        1.541754

   r2_precip_depth_1_hr_site_std  r2_precip_depth_1_hr_site_z  \
0                      13.921711                    -0.110745
1                      13.921711                    -0.110745
2                      13.921711                    -0.110745
3                      13.921711                    -0.110745
4                      13.921711                    -0.110745

   r2_precip_depth_1_hr_site_pos
0                            0.0
1                            0.0
2                            0.0
3                            0.0
4                            0.0

[5 rows x 59 columns]

C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):

  building_id ts_idx pair_id primary_use  square_feet  year_built  \
0           0   3384       0   Education         7432      2008.0
1           1   3384       4   Education         2720      2004.0
2           2   3384       8   Education         5376      1991.0
3           3   3384      12   Education        23685      2002.0
4           4   3384      16   Education       116607      1975.0

   floor_count       timestamp_gmt  time_diff_hours  air_temperature  ...  \
0          NaN 2016-05-21 04:00:00              4.0             25.0  ...
1          NaN 2016-05-21 04:00:00              4.0             25.0  ...
2          NaN 2016-05-21 04:00:00              4.0             25.0  ...
3          NaN 2016-05-21 04:00:00              4.0             25.0  ...
4          NaN 2016-05-21 04:00:00              4.0             25.0  ...

   r4_wind_speed_lag24  r4_wind_speed_diff_lag24  r4_wind_speed_rollmean3  \
0                  0.0                       1.5                      0.5
1                  0.0                       1.5                      0.5
2                  0.0                       1.5                      0.5
3                  0.0                       1.5                      0.5
4                  0.0                       1.5                      0.5

   r4_wind_speed_anom3  r4_wind_speed_rollmean24  r4_wind_speed_anom24  \
0                  1.0                    2.2125               -0.7125
1                  1.0                    2.2125               -0.7125
2                  1.0                    2.2125               -0.7125
3                  1.0                    2.2125               -0.7125
4                  1.0                    2.2125               -0.7125

   r4_te_primary_use_meter_mean  r4_te_primary_use_meter_count  \
0                      4.420451                      4348683.0
1                      4.420451                      4348683.0
2                      4.420451                      4348683.0
3                      4.420451                      4348683.0
4                      4.420451                      4348683.0

   r4_te_site_meter_mean  r4_te_site_meter_count
0               4.092927                550080.0
1               4.092927                550080.0
2               4.092927                550080.0
3               4.092927                550080.0
4               4.092927                550080.0

[5 rows x 97 columns]

C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):

  building_id ts_idx pair_id primary_use  square_feet  year_built  \
0           0   3384       0   Education         7432      2008.0
1           1   3384       4   Education         2720      2004.0
2           2   3384       8   Education         5376      1991.0
3           3   3384      12   Education        23685      2002.0
4           4   3384      16   Education       116607      1975.0

   floor_count       timestamp_gmt  time_diff_hours  air_temperature  ...  \
0          NaN 2016-05-21 04:00:00              4.0             25.0  ...
1          NaN 2016-05-21 04:00:00              4.0             25.0  ...
2          NaN 2016-05-21 04:00:00              4.0             25.0  ...
3          NaN 2016-05-21 04:00:00              4.0             25.0  ...
4          NaN 2016-05-21 04:00:00              4.0             25.0  ...

   site_id  meter  r5_local_hour  r5_local_weekday  r5_local_dayofyear  \
0        0      0             20                 4                 141
1        0      0             20                 4                 141
2        0      0             20                 4                 141
3        0      0             20                 4                 141
4        0      0             20                 4                 141

   r5_is_weekend_local  r5_is_day_off_or_holiday  r5_frac_primary_use_hour  \
0                    0                         0                  0.943449
1                    0                         0                  0.943449
2                    0                         0                  0.943449
3                    0                         0                  0.943449
4                    0                         0                  0.943449

   r5_frac_primary_use_weekday  r5_frac_primary_use_dayofyear
0                     1.005951                       0.999501
1                     1.005951                       0.999501
2                     1.005951                       0.999501
3                     1.005951                       0.999501
4                     1.005951                       0.999501

[5 rows x 43 columns]

C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):

  building_id ts_idx pair_id primary_use  square_feet  year_built  \
0           0   3384       0   Education         7432      2008.0
1           1   3384       4   Education         2720      2004.0
2           2   3384       8   Education         5376      1991.0
3           3   3384      12   Education        23685      2002.0
4           4   3384      16   Education       116607      1975.0

   floor_count       timestamp_gmt  time_diff_hours  air_temperature  ...  \
0          NaN 2016-05-21 04:00:00              4.0             25.0  ...
1          NaN 2016-05-21 04:00:00              4.0             25.0  ...
2          NaN 2016-05-21 04:00:00              4.0             25.0  ...
3          NaN 2016-05-21 04:00:00              4.0             25.0  ...
4          NaN 2016-05-21 04:00:00              4.0             25.0  ...

   r25_site_missing_rate_precip_depth_1_hr  r25_is_missing_sea_level_pressure  \
0                                      0.0                                  0
1                                      0.0                                  0
2                                      0.0                                  0
3                                      0.0                                  0
4                                      0.0                                  0

   r25_site_missing_rate_sea_level_pressure  r25_is_missing_wind_direction  \
0                                       0.0                              0
1                                       0.0                              0
2                                       0.0                              0
3                                       0.0                              0
4                                       0.0                              0

   r25_site_missing_rate_wind_direction  r25_is_missing_wind_speed  \
0                                   0.0                          0
1                                   0.0                          0
2                                   0.0                          0
3                                   0.0                          0
4                                   0.0                          0

   r25_site_missing_rate_wind_speed  r25_missing_weather_count  \
0                               0.0                        0.0
1                               0.0                        0.0
2                               0.0                        0.0
3                               0.0                        0.0
4                               0.0                        0.0

   r25_missing_weather_frac  r25_site_any_missing_rate
0                       0.0                        0.0
1                       0.0                        0.0
2                       0.0                        0.0
3                       0.0                        0.0
4                       0.0                        0.0

[5 rows x 52 columns]

C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):
C:\Users\zpz\AppData\Local\Temp\ipykernel_31880\3730604924.py:73: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s) or pd.api.types.is_categorical_dtype(s):

,set_name,n_rows_used,n_input_features,n_numeric_features,n_discrete_features,set_cv_r2,set_cv_rmse,ridge_alpha,n_splits,sample_size,delta_r2_vs_base,delta_rmse_vs_base
0,base_only,2000000,35,21,14,0.050326,2412.215022,1.0,3,2000000,0.000000e+00,0.000000e+00
1,base_plus_expert,2000000,51,37,14,0.050326,2412.215022,1.0,3,2000000,9.804602e-12,-1.245235e-08
2,base_plus_rank2,2000000,59,45,14,0.050326,2412.215022,1.0,3,2000000,4.630141e-11,-5.880383e-08
3,base_plus_rank4,2000000,97,83,14,0.054520,2406.883841,1.0,3,2000000,4.193065e-03,-5.331181e+00
4,base_plus_rank5,2000000,43,27,16,0.050326,2412.215022,1.0,3,2000000,2.220013e-11,-2.819479e-08
5,base_plus_rank25,2000000,52,22,30,0.050326,2412.215022,1.0,3,2000000,5.773160e-15,-7.275958e-12

In [19]:
for _, row in feature_set_results.iterrows():
    print(
        f"{row['set_name']}: "
        f"R2={row['set_cv_r2']:.6f}, "
        f"RMSE={row['set_cv_rmse']:.6f}, "
        f"ΔR2_vs_base={row['delta_r2_vs_base']:.6f}, "
        f"ΔRMSE_vs_base={row['delta_rmse_vs_base']:.6f}, "
        f"rows={row['n_rows_used']}, "
        f"input_features={row['n_input_features']}"
    )

base_only: R2=0.050326, RMSE=2412.215022, ΔR2_vs_base=0.000000, ΔRMSE_vs_base=0.000000, rows=2000000, input_features=35
base_plus_expert: R2=0.050326, RMSE=2412.215022, ΔR2_vs_base=0.000000, ΔRMSE_vs_base=-0.000000, rows=2000000, input_features=51
base_plus_rank2: R2=0.050326, RMSE=2412.215022, ΔR2_vs_base=0.000000, ΔRMSE_vs_base=-0.000000, rows=2000000, input_features=59
base_plus_rank4: R2=0.054520, RMSE=2406.883841, ΔR2_vs_base=0.004193, ΔRMSE_vs_base=-5.331181, rows=2000000, input_features=97
base_plus_rank5: R2=0.050326, RMSE=2412.215022, ΔR2_vs_base=0.000000, ΔRMSE_vs_base=-0.000000, rows=2000000, input_features=43
base_plus_rank25: R2=0.050326, RMSE=2412.215022, ΔR2_vs_base=0.000000, ΔRMSE_vs_base=-0.000000, rows=2000000, input_features=52